# validation

- name: assert all vars are set
  assert: 
    that:
      - item is defined
      - item | length > 0
    quiet: true
  loop:
  - java_version
  - java_home
  - temp_folder
  - java_download_filename
  - java_download_url
  - java_installation_folder
  - java_bin


# validate if installed

- name: Check if java exists
  stat:
    path: "{{ java_bin }}"
  register: java_exists

# install java

- name: install java
  block:

    - name: make sure temp folder
      file:
        path: "{{ temp_folder }}"
        state: directory
        owner: "{{ ansible_user_id }}"
      become: yes
    
    - name: download java from s3 url
      get_url:
        url: "{{ java_download_url }}"
        dest: "{{ temp_folder }}/{{ java_download_filename }}"
        timeout: "{{ download_timeout | default(60) }}"
      become: yes
      when: custom_download_url == ""

    - name: download zip from custom url
      get_url:
        url: "{{ custom_download_url }}"
        dest: "{{ temp_folder }}/{{ java_download_filename }}"
        timeout: "{{ download_timeout | default(60) }}"
      when: custom_download_url != ""
    
    - name: make sure java installation folder exists
      file:
        path: "{{ java_installation_folder }}"
        state: directory
        owner: "{{ ansible_user_id }}"
      become: yes
    
    - name: unzip java file
      command: "tar -xzvf {{ temp_folder }}/{{ java_download_filename }} -C {{ java_installation_folder }}"
      args:
        creates: "{{ java_bin }}"
      become: yes
      register: unzip_java
      ignore_errors: yes
    
    - name: sleep for 25 seconds if unzip java fails
      pause:
        seconds: 25
      when: unzip_java.rc != 0

    - name: rerun - unzip java file if first fails
      command: "tar -xzvf {{ temp_folder }}/{{ java_download_filename }} -C {{ java_installation_folder }}"
      args:
        creates: "{{ java_bin }}"
      become: yes
      when: unzip_java.rc != 0

  when: not java_exists.stat.exists


# set java to global environment path

- name: 
  block:

    - name: make sure ~/.bashrc exists
      stat:
        path: ~/.bashrc
      register: bashrc_exists
    
    - name: create if ~/.bashrc not exists
      file:
        path: ~/.bashrc
        state: touch
      when: not bashrc_exists.stat.exists
    
    - name: Set JAVA_HOME
      lineinfile:
        dest: ~/.bashrc
        state: present
        regexp: "^export JAVA_HOME="
        line: "export JAVA_HOME={{ java_home }}"
    
    - name: Set JAVA PATH
      lineinfile:
        dest: ~/.bashrc
        state: present
        regexp: "^export PATH="
        line: "export PATH={{ java_home }}/Contents/Home/bin:/usr/local/bin:$PATH"
    
    - name: add bashrc to bash_profile
      lineinfile:
        dest: ~/.bash_profile
        state: present
        regexp: "if [ -f ~/.bashrc ]"
        line: "if [ -f ~/.bashrc ]; then . ~/.bashrc; fi"
        insertbefore: BOF

  when: update_java_path == True

# validate java

- name: make sure java is installed on the machine
  command: "{{ java_bin }} -version"
  register: java_test
  ignore_errors: yes

- name: fail if java is not found
  fail:
    msg: java must be accesible in path
  when: java_test.rc != 0

# expose role output 

- name: sanitize role name
  set_fact:
    sanitize_role_name: "{{ role_name | replace('-', '_') | regex_replace('([^A-Za-z0-9_])', '') | trim }}"

- name: expose role output
  set_fact:
    "{{ sanitize_role_name }}":
      java_home: "{{ java_home }}"
      java_bin: "{{ java_bin }}"